### ISSUE TITLE
Entries on plots not accurate

### ISSUE THREAD

**Issue by SekhmetLightblade** [zhudotexe/zhu.codes#7]
I was searching for a house and noticed that 
shiro 28,24 - site says 58... actual bidders... 1
shiro 29, 13 site says 55 act
shiro ward 11,8 site says 6 actual bidders.... 6ual bidders.... 0

So some of them are not accurate and I dont know if you all know or not.

**Comment by zhudotexe** [comment]
Weird. I'm looking into it.

**Comment by zhudotexe** [comment]
Fixed by https://github.com/zhudotexe/FFXIV_PaissaDB/commit/79b591ea593c18e451af3b2aa938bf3c05813bd8

**Comment by SekhmetLightblade** [comment]
> Weird. I'm looking into it.

Its still not working right... if you need to know the DC and Server let me know?

![image_2023-07-23_185402491](https://github.com/zhudotexe/zhu.codes/assets/85028807/105fa51f-4bad-41d2-af6a-f7ac09e04fc9)

**Comment by zhudotexe** [comment]
I don't see the error in that screenshot - the placard says W28P24 has 11 entries, which agrees with the website.

**Comment by SekhmetLightblade** [comment]
That was my mistake I didn't notice the screen refresh when I took the SS. Thank you for fixing it!
